version: '3'

networks:
  ansible-net:
    name: ansible-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24

services:
  ansible-control:
    image: ansible-control:1.1
    container_name: ansible-control
    hostname: ansible-control
    networks:
      - ansible-net
    ports:
      - "2222:22"
    volumes:
      - ./ansible:/etc/ansible

  ansible-node1:
    image: ansible-node:1.0
    container_name: ansible-node1
    hostname: ansible-node1
    networks:
      - ansible-net
    environment:
      - "AUTHORIZED_KEYS=/home/ansible/.ssh/authorized_keys"

  ansible-node2:
    image: ansible-node:1.0
    container_name: ansible-node2
    hostname: ansible-node2
    networks:
      - ansible-net
    environment:
      - "AUTHORIZED_KEYS=/home/ansible/.ssh/authorized_keys"

  ansible-webserver-python1:
    image: ansible-webserver-python:0.1
    container_name: ansible-webserver-python1
    hostname: ansible-webserver-python1
    networks:
      - ansible-net
    ports:
      - "5001:5001"  # Web server will be available on localhost:5000
    environment:
      - DOCKER_HOST=tcp://docker:2375  # If connecting to Docker via TCP