version: "3.8"
services:
  system:
    image: "emerson-ubuntu"
    container_name: emerson-ubuntu
    build: .
    tty: true
    ports:
      - "1001:1001"   
    command: 
      - /bin/sh
      - -c
      - |
        apt-get update
        apt-get install -y net-tools
        tail -f /etc/hosts

#Add created container network
networks:
  default:
    name: container-lab
    external: true