version: '3'

networks:
  ansible-net:
    name: ansible-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24

services:
  ansible-control:
    build:
      context: .
      dockerfile: Control.Dockerfile
    container_name: ansible-control
    hostname: ansible-control
    networks:
      - ansible-net
    ports:
      - "2222:22"
    volumes:
      - ./ansible:/etc/ansible

  ansible-node1:
    build:
      context: .
      dockerfile: Node.Dockerfile
    container_name: ansible-node1
    hostname: ansible-node1
    networks:
      - ansible-net
    environment:
      - "AUTHORIZED_KEYS=/home/ansible/.ssh/authorized_keys"

  ansible-node2:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: ansible-node2
    hostname: ansible-node2
    networks:
      - ansible-net
    environment:
      - "AUTHORIZED_KEYS=/home/ansible/.ssh/authorized_keys"
