version: "3.8"
services:
  system:
    image: "emerson-pwsh"
    hostname: emerson-pwsh-001
    container_name: emerson-pwsh
    build: .
    tty: true
    command:
      - pwsh
      - -command
      - |
        Find-Module LocalAccountManagement | Install-Module -Confirm:$false -Force -SkipPublisherCheck | Out-Null
        Find-Module PSWSMAN | Install-Module -Confirm:$false -Force -SkipPublisherCheck | Out-Null
        Install-WSMan -Confirm:$false | Out-Null
        Get-Content /etc/hosts -Tail 1 -Wait
