version: "3.8"
services:
  system:
    image: "emerson-pwsh"
    hostname: emerson-pwsh-001
    container_name: emerson-pwsh
    build: .
    tty: true
    command:
      - pwsh
      - -command
      - |
        Find-Module LocalAccountManagement | Install-Module -Force -Verbose
        Get-Content /etc/hosts -Tail 1 -Wait
