version: "3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    #image: "redis:alpine"
    image: "github-python-cicd"

#version: "3"
#services:
#  website:
#    image: nginx
#    ports:
#      - "8081:80"
#    restart: always