version: "3.8"
services:
  system:
    image: "emerson-alpine"
    container_name: emerson-alpine
    build: .
    tty: true
    ports:
      - "1000:1000"
    command: 
      - /bin/sh
      - -c
      - |
        tail -f /etc/hosts

#Add created container network
#10.1.200.0/16
networks:
  default:
    name: container-lab
    external: true
    