version: "3.8"
services:
  system:
    image: "emerson-alpine"
    container_name: emerson-alpine
    build: .
    tty: true
    command: 
      - /bin/sh
      - -c
      - |
        apt-get update
        apt-get install -y net-tools
        tail -f /etc/hosts
    ports:
      - "1002:1002"
    