version: "3.8"
services:
  system:
    image: "twitter:v1.0.0.0"
    container_name: emerson-twitter
    build: .
    tty: true
    command: 
      - /bin/sh
      - -c
      - |
        tail -f /etc/hosts
    