version: "3.8"
services:
  system:
    image: "emerson-nodejs"
    container_name: emerson-nodejs
    build: .
    tty: true
    working_dir: /usr/local/bin/nodechat/src
    ports: 
      - "3000:3000"
      - "22:22"
    command: 
      - /bin/sh
      - -c
      - |
        npm install 
        npm audit fix --force 
        npm start 

#Add created container network
networks:
  default:
    name: container-lab
    external: true