name: Alpine Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
    - 'repos/src/_alpine_1/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'repos/src/_alpine_1/**'

env:
  WORKDIR: /opt/actions-runner/_work/Docker/Docker/repos/src/_alpine_1/
  IMAGENAME: emerson-alpine

jobs:

  stage:
    name: Stage Imaging Environment
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Stop ANY running containers
      run: docker ps --filter "name=${{env.IMAGENAME}}" -q | xargs docker stop || echo "No running containers found..."
    - name: Stop ANY composed from the current working-directory
      working-directory: ${{env.WORKDIR}}
      run: docker compose down
    - name: Remove previous build container
      run: docker rmi ${{env.IMAGENAME}} -f 
    - name: Remove ANY dangling Docker Images
      run: docker images --filter "dangling=true" -q || xargs docker image rm
    - name: Clean Docker system cache
      run: docker system prune --filter "label!=lab" -f

  build:
    name: Build Docker Image
    needs: stage
    runs-on: self-hosted
    steps:
    - name: Build from the Dockerfile
      working-directory: ${{env.WORKDIR}}
      run: docker build . -t ${{env.IMAGENAME}}
  
  test:
    name: Scan Docker Image & containers
    needs: build
    runs-on: self-hosted
    steps:
      - name: Scan the Docker Image with Snyk
        run: snyk container test ${{env.IMAGENAME}} || true

  deploy:
    name: Compose Docker Image and start Container
    needs: test
    runs-on: self-hosted
    steps:
    - name: Compose the Docker Image
      working-directory: ${{env.WORKDIR}}
      run: docker compose up -d 
        