name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  stage:
    name: Stage Imaging Environment
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Stop ANY running containers
      run: docker ps -aq | xargs docker stop 
    - name: Stop ANY composed from the current working-directory
      working-directory: /opt/actions-runner/_work/Docker/Docker/repos/scratch/_python_1
      run: docker compose down
    - name: Clean Docker system cache
      run: docker system prune -f

  build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
    - name: Build from the Dockerfile
      working-directory: /opt/actions-runner/_work/Docker/Docker/repos/scratch/_python_1
      run: docker build . 
    - name: Compose the Docker Image
      working-directory: /opt/actions-runner/_work/Docker/Docker/repos/scratch/_python_1
      run: docker compose up -d 