name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: pwd && ls -lart
      run: cd .github/workflows/
      run: docker build -t docker-cicd-image:$(date +%s) .
