name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set the working directory (test)
      working-directory: /opt/actions-runner/_work/Docker/Docker/repos/scratch/_python_1
      run: pwd && ls -lart
    - name: Build from the Dockerfile
      working-directory: /opt/actions-runner/_work/Docker/Docker/repos/scratch/_python_1
      run: docker build . -t docker-cicd-image:$(date +%s)
